### ISSUE TITLE
overload.hpp simplification?

### ISSUE THREAD

**Issue by cppljevans** [viboes/tags#6]
It took me a while to figure how code in overload.hpp works.  IIUC,
it produces a recursively inherited overloader.  For example for:

``` c++
  overload(F1 && f1,  F2 && f2,  F3 && f3,  F4 && f4)
```

it produces the overloader 14 defined as:

``` c++
  using  overloader12=overloader<F1,F2>;
  using  overloader13=overloader<overloader12,F3>;
  using  overloader14=overloader<overloader13,F4>;
```

Since the only purpose is to "mixin" all the f's into
one superclass as overloaded call operators, why
not simplify the code using an overloader shown
in the following?

``` c++
//Purpose:
//  See if can multi-inherit classes
//  with member function with same
//  name but different signature.
//
//Result:
//  Works.
//   
//=========== 
#include <iostream>
template<int I>
struct udt_i
/**@brief
 *  User Defined Type.
 */
{
      friend 
    std::ostream&
  operator<<
    ( std::ostream& os
    , udt_i const&
    )
    { return os<<"udt_i<"<<I<<">";
    }
};
template<int I>
struct functor_i
/**@brief
 *  User Defined Functor.
 */
{
  using arg_t=udt_i<I>;
  void operator()(arg_t const&a)
  { std::cout<<"functor_i<"<<I<<">::operator()("<<a<<" const&).\n";
  }
};
template<typename Functor>
struct forwarder
/**@brief
 *  this->operator() forwards to Functor::operator()
 */
{
  Functor functor_v;
  forwarder(Functor const& functor_a)
    : functor_v(functor_a)
  {}  
  using arg_t=typename Functor::arg_t;
  void operator()(arg_t const&arg_v)
  { functor_v(arg_v);
  }
};
template<typename... Functors>
struct overloader
/**@brief
 *  "Mixin" all the Functors::operator()'s
 *  into this class.
 */
: public forwarder<Functors>...
{
  overloader(Functors&&... functors_a)
  : forwarder<Functors>(functors_a)...
  {}  
};
int main()
{
    overloader
    < functor_i<0>
    , functor_i<1>
    , functor_i<2>
    > 
  ovldr
    ( functor_i<0>{}
    , functor_i<1>{}
    , functor_i<2>{}
    ) 
    ;
  ovldr(udt_i<0>{});
  ovldr(udt_i<1>{});
  ovldr(udt_i<2>{});
  return 0;
}  
```

This code produces output

```
functor_i<0>::operator()(udt_i<0> const&).
functor_i<1>::operator()(udt_i<1> const&).
functor_i<2>::operator()(udt_i<2> const&).
```

**Comment by viboes** [comment]
I agree your implementation is simpler. However I'm getting

```
darwin.compile.c++ bin/overload_include_p.test/darwin-5.1.0_14/debug/link-static/overload/include_pass.o
overload/include_pass.cpp: In function ‘int main()’:
overload/include_pass.cpp:123:19: erreur: request for member ‘operator()’ is ambiguous
   ovldr(udt_i<0>{});
                   ^
overload/include_pass.cpp:90:10: note: candidats sont: void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<2>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<2>]
     void operator()(arg_t const&arg_v)
          ^
overload/include_pass.cpp:90:10: note:                 void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<1>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<1>]
overload/include_pass.cpp:90:10: note:                 void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<0>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<0>]
overload/include_pass.cpp:124:19: erreur: request for member ‘operator()’ is ambiguous
   ovldr(udt_i<1>{});
                   ^
overload/include_pass.cpp:90:10: note: candidats sont: void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<2>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<2>]
     void operator()(arg_t const&arg_v)
          ^
overload/include_pass.cpp:90:10: note:                 void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<1>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<1>]
overload/include_pass.cpp:90:10: note:                 void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<0>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<0>]
overload/include_pass.cpp:125:19: erreur: request for member ‘operator()’ is ambiguous
   ovldr(udt_i<2>{});
                   ^
overload/include_pass.cpp:90:10: note: candidats sont: void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<2>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<2>]
     void operator()(arg_t const&arg_v)
          ^
overload/include_pass.cpp:90:10: note:                 void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<1>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<1>]
overload/include_pass.cpp:90:10: note:                 void cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor = cppljevans::functor_i<0>; cppljevans::forwarder<Functor>::arg_t = cppljevans::udt_i<0>]

    "/usr/gcc-5.1.0/bin/g++-5.1.0"  -ftemplate-depth-128 -fstack-protector-all -std=c++14 -Wno-unused-local-typedefs -Wno-variadic-macros -Wno-unused-function -O0 -fno-inline -Wall -g -gdwarf-2 -fexceptions    -I"." -I"../include" -I"/Users/viboes/github/modular-boost3" -I"/Users/viboes/github/optional" -c -o "bin/overload_include_p.test/darwin-5.1.0_14/debug/link-static/overload/include_pass.o" "overload/include_pass.cpp"

...failed darwin.compile.c++ bin/overload_include_p.test/darwin-5.1.0_14/debug/link-static/overload/include_pass.o...
...failed updating 1 target...
```

IMO, there is a missing using in overloader

``` c++
using forwarder<Functors>::operator();...
```

But this is not correct in C++14. My implementation uses `F12==detail::overloader<F1,F2>`to workaround this limitation. 

Which compiler have you used?

**Comment by cppljevans** [comment]
On 09/26/2015 06:45 AM, Vicente J. Botet Escriba wrote:

> I agree your implementation is simpler. However I'm getting
> 
> |darwin.compile.c++
> bin/overload_include_p.test/darwin-5.1.0_14/debug/link-static/overload/include_pass.o
> overload/include_pass.cpp: In function ‘int main()’:
> overload/include_pass.cpp:123:19: erreur: request for member
> ‘operator()’ is ambiguous ovldr(udt_i<0>{}); ^
> overload/include_pass.cpp:90:10: note: candidats sont: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<2>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<2>] void operator()(arg_t const&arg_v) ^
> overload/include_pass.cpp:90:10: note: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<1>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<1>] overload/include_pass.cpp:90:10: note: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<0>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<0>] overload/include_pass.cpp:124:19: erreur:
> request for member ‘operator()’ is ambiguous ovldr(udt_i<1>{}); ^
> overload/include_pass.cpp:90:10: note: candidats sont: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<2>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<2>] void operator()(arg_t const&arg_v) ^
> overload/include_pass.cpp:90:10: note: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<1>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<1>] overload/include_pass.cpp:90:10: note: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<0>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<0>] overload/include_pass.cpp:125:19: erreur:
> request for member ‘operator()’ is ambiguous ovldr(udt_i<2>{}); ^
> overload/include_pass.cpp:90:10: note: candidats sont: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<2>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<2>] void operator()(arg_t const&arg_v) ^
> overload/include_pass.cpp:90:10: note: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<1>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<1>] overload/include_pass.cpp:90:10: note: void
> cppljevans::forwarder<Functor>::operator()(const arg_t&) [with Functor
> = cppljevans::functor_i<0>; cppljevans::forwarder<Functor>::arg_t =
> cppljevans::udt_i<0>] "/usr/gcc-5.1.0/bin/g++-5.1.0"
> -ftemplate-depth-128 -fstack-protector-all -std=c++14
> -Wno-unused-local-typedefs -Wno-variadic-macros -Wno-unused-function
> -O0 -fno-inline -Wall -g -gdwarf-2 -fexceptions -I"." -I"../include"
> -I"/Users/viboes/github/modular-boost3"
> -I"/Users/viboes/github/optional" -c -o
> "bin/overload_include_p.test/darwin-5.1.0_14/debug/link-static/overload/include_pass.o"
> "overload/include_pass.cpp" ...failed darwin.compile.c++
> bin/overload_include_p.test/darwin-5.1.0_14/debug/link-static/overload/include_pass.o...
> ...failed updating 1 target... |
> 
> Which compiler have you used?
> 
> Vicente,

I did not try to compile overload/include_pass.cpp.  I just tried
the little test program which was included in my previous message
and which I've attached to this reply.

The compiler I used was clang3.7 and it worked.
However, I tried compilation with gcc5.2.0 and got what's
shown in 2nd attachment, which did not work :(

-regards,
Larry

-_\- mode: compilation; default-directory: "~/prog_dev/clang/" -_-
Compilation started at Sat Sep 26 07:32:39

make run
install -d `dirname /tmp/build/gcc5_2_0/clang/multi_inherit_funcs.o`
/home/evansl/dwnlds/gcc/5.2.0/install/bin/g++ -c    -std=c++14 -Wno-deprecated  -I/home/evansl/prog_dev/boost/sandbox/rw/sandbox/ldionne/hana/include -I/home/evansl/prog_dev/boost/sandbox/rw/non_variadic_templates -I/home/evansl/prog_dev/clang/libcxx/sandbox/libs/composite_storage/include -I/home/evansl/prog_dev/boost/sandbox/rw/sandbox/lje -I/home/evansl/prog_dev/boost/boost-releases/ro/boost_1_59_0    -ftemplate-depth=100  multi_inherit_funcs.cpp -MMD -o /tmp/build/gcc5_2_0/clang/multi_inherit_funcs.o 
multi_inherit_funcs.cpp: In function ‘int main()’:
multi_inherit_funcs.cpp:77:19: error: request for member ‘operator()’ is ambiguous
   ovldr(udt_i<0>{});
                   ^
multi_inherit_funcs.cpp:48:8: note: candidates are: void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<2>; forwarder<Functor>::arg_t = udt_i<2>]
   void operator()(arg_t const&arg_v)
        ^
multi_inherit_funcs.cpp:48:8: note:                 void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<1>; forwarder<Functor>::arg_t = udt_i<1>]
multi_inherit_funcs.cpp:48:8: note:                 void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<0>; forwarder<Functor>::arg_t = udt_i<0>]
multi_inherit_funcs.cpp:78:19: error: request for member ‘operator()’ is ambiguous
   ovldr(udt_i<1>{});
                   ^
multi_inherit_funcs.cpp:48:8: note: candidates are: void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<2>; forwarder<Functor>::arg_t = udt_i<2>]
   void operator()(arg_t const&arg_v)
        ^
multi_inherit_funcs.cpp:48:8: note:                 void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<1>; forwarder<Functor>::arg_t = udt_i<1>]
multi_inherit_funcs.cpp:48:8: note:                 void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<0>; forwarder<Functor>::arg_t = udt_i<0>]
multi_inherit_funcs.cpp:79:19: error: request for member ‘operator()’ is ambiguous
   ovldr(udt_i<2>{});
                   ^
multi_inherit_funcs.cpp:48:8: note: candidates are: void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<2>; forwarder<Functor>::arg_t = udt_i<2>]
   void operator()(arg_t const&arg_v)
        ^
multi_inherit_funcs.cpp:48:8: note:                 void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<1>; forwarder<Functor>::arg_t = udt_i<1>]
multi_inherit_funcs.cpp:48:8: note:                 void forwarder<Functor>::operator()(const arg_t&) [with Functor = functor_i<0>; forwarder<Functor>::arg_t = udt_i<0>]
make: **\* [/tmp/build/gcc5_2_0/clang/multi_inherit_funcs.o] Error 1

Compilation exited abnormally with code 2 at Sat Sep 26 07:32:39

**Comment by viboes** [comment]
Is this a bug on clang or on gcc?
I believe that gcc conforms to the standard here.

**Comment by cppljevans** [comment]
However, using recursive inheritance make g++ happy:

``` c++
//Purpose:
//  See if can multi-inherit classes
//  with member function with same
//  name but different signature.
//
//Result:
//  Works.
//   
//=========== 
#include <iostream>
template<int I>
struct udt_i
/**@brief
 *  User Defined Type.
 */
{
      friend 
    std::ostream&
  operator<<
    ( std::ostream& os
    , udt_i const&
    )
    { return os<<"udt_i<"<<I<<">";
    }
};
template<int I>
struct functor_i
/**@brief
 *  User Defined Functor.
 */
{
  using arg_t=udt_i<I>;
  void operator()(arg_t const&a)
  { std::cout<<"functor_i<"<<I<<">::operator()("<<a<<" const&).\n";
  }
};
template<typename Functor>
struct forwarder
/**@brief
 *  this->operator() forwards to Functor::operator()
 */
{
  Functor functor_v;
  forwarder(Functor const& functor_a)
    : functor_v(functor_a)
  {}  
  using arg_t=typename Functor::arg_t;
  void operator()(arg_t const&arg_v)
  { functor_v(arg_v);
  }
};
#ifdef __clang__
template<typename... Functors>
struct overloader
/**@brief
 *  "Mixin" all the Functors::operator()'s
 *  into this class.
 */
: public forwarder<Functors>...
{
  overloader(Functors&&... functors_a)
  : forwarder<Functors>(functors_a)...
  {}  
};
#else
template<typename... Functors>
struct overloader
/**@brief
 *  "Mixin" all the Functors::operator()'s
 *  into this class.
 */
  ;
template<>
struct overloader<>
{
  void operator()()
  {
  }
};
template<typename Functor0, typename... Functors>
struct overloader<Functor0, Functors...>
: public forwarder<Functor0>, overloader<Functors...>
{
  overloader(Functor0&& functor0, Functors&&... functors_a)
  : forwarder<Functor0>(std::forward<Functor0>(functor0))
  , overloader<Functors...>(std::forward<Functors>(functors_a)...)
  {}
  using forwarder<Functor0>::operator();
  using overloader<Functors...>::operator();
};
#endif
int main()
{
    overloader
    < functor_i<0>
    , functor_i<1>
    , functor_i<2>
    > 
  ovldr
    ( functor_i<0>{}
    , functor_i<1>{}
    , functor_i<2>{}
    ) 
    ;
  ovldr(udt_i<0>{});
  ovldr(udt_i<1>{});
  ovldr(udt_i<2>{});
  return 0;
}  

```

**Comment by viboes** [comment]
Thanks, this works now. I will ask on std-proposal as follow up of my post on the proposal P0051.

**Comment by viboes** [comment]
https://github.com/viboes/tags/commit/c12af881f0ddf9a82b6f0d069be90fb2aa865ff3
